 (define (domain sokoban-domain)
	(:requirements :strips)
	(:predicates (BLOCK ?block) 
		(BOT ?bot) 
		(At ?bot ?loc) 
		(NextTo ?locA ?locB ?direction) 
		(Empty ?loc) )
	(:action moveBot
		:parameters(?locA ?locB ?bot ?direction)
		:precondition ( and (BOT ?bot) 
			(NextTo ?locA ?locB ?direction) 
			(At ?bot ?locA) 
			(Empty ?locB))
		:effect (and ( not (Empty ?locB) )
			(At ?bot ?locB) 
			(Empty ?locA) 
			(not (At ?bot ?locA))))
	(:action moveBlock
		:parameters (?locA ?locB ?locC ?bot ?block ?direction)

		:precondition (and (BOT ?bot) 
			(BLOCK ?block) 
			(At ?bot ?locA) 
			(At ?block ?locB) 
			(Empty ?locC) 
			(NextTo ?locA ?locB ?direction) 
			(NextTo ?locB ?locC ?direction) )

		:effect (and (Empty ?locA) 
			(not (At ?bot ?locA)) 
			(not (At ?block ?locB)) 
			(At ?bot ?locB)(not(Empty ?locB)) (not(Empty ?locC))
			(At ?block ?locC) )))
